// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqxebbiumqqrihxaugmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeGViYml1bXFxcmloeGF1Z21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDA5NDEsImV4cCI6MjA1ODUxNjk0MX0.Qh5pMxm1HC2fbYIAXsGQP1doknIBNKHs7PjljwEeALE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);